// Generated by gencpp from file robot_msgs/ChangeColor.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_CHANGECOLOR_H
#define ROBOT_MSGS_MESSAGE_CHANGECOLOR_H

#include <ros/service_traits.h>


#include <robot_msgs/ChangeColorRequest.h>
#include <robot_msgs/ChangeColorResponse.h>


namespace robot_msgs
{

struct ChangeColor
{

typedef ChangeColorRequest Request;
typedef ChangeColorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeColor
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::ChangeColor > {
  static const char* value()
  {
    return "b6666a3f837cecf81b427d119a6ab66e";
  }

  static const char* value(const ::robot_msgs::ChangeColor&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::ChangeColor > {
  static const char* value()
  {
    return "robot_msgs/ChangeColor";
  }

  static const char* value(const ::robot_msgs::ChangeColor&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::ChangeColorRequest> should match
// service_traits::MD5Sum< ::robot_msgs::ChangeColor >
template<>
struct MD5Sum< ::robot_msgs::ChangeColorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::ChangeColor >::value();
  }
  static const char* value(const ::robot_msgs::ChangeColorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::ChangeColorRequest> should match
// service_traits::DataType< ::robot_msgs::ChangeColor >
template<>
struct DataType< ::robot_msgs::ChangeColorRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::ChangeColor >::value();
  }
  static const char* value(const ::robot_msgs::ChangeColorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::ChangeColorResponse> should match
// service_traits::MD5Sum< ::robot_msgs::ChangeColor >
template<>
struct MD5Sum< ::robot_msgs::ChangeColorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::ChangeColor >::value();
  }
  static const char* value(const ::robot_msgs::ChangeColorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::ChangeColorResponse> should match
// service_traits::DataType< ::robot_msgs::ChangeColor >
template<>
struct DataType< ::robot_msgs::ChangeColorResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::ChangeColor >::value();
  }
  static const char* value(const ::robot_msgs::ChangeColorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_CHANGECOLOR_H
