// Generated by gencpp from file robot_msgs/MoveToPoseGoal.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_MOVETOPOSEGOAL_H
#define ROBOT_MSGS_MESSAGE_MOVETOPOSEGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace robot_msgs
{
template <class ContainerAllocator>
struct MoveToPoseGoal_
{
  typedef MoveToPoseGoal_<ContainerAllocator> Type;

  MoveToPoseGoal_()
    : target_pose()  {
    }
  MoveToPoseGoal_(const ContainerAllocator& _alloc)
    : target_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _target_pose_type;
  _target_pose_type target_pose;





  typedef boost::shared_ptr< ::robot_msgs::MoveToPoseGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::MoveToPoseGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToPoseGoal_

typedef ::robot_msgs::MoveToPoseGoal_<std::allocator<void> > MoveToPoseGoal;

typedef boost::shared_ptr< ::robot_msgs::MoveToPoseGoal > MoveToPoseGoalPtr;
typedef boost::shared_ptr< ::robot_msgs::MoveToPoseGoal const> MoveToPoseGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::MoveToPoseGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::MoveToPoseGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::MoveToPoseGoal_<ContainerAllocator1> & lhs, const ::robot_msgs::MoveToPoseGoal_<ContainerAllocator2> & rhs)
{
  return lhs.target_pose == rhs.target_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::MoveToPoseGoal_<ContainerAllocator1> & lhs, const ::robot_msgs::MoveToPoseGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::MoveToPoseGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::MoveToPoseGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::MoveToPoseGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::MoveToPoseGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::MoveToPoseGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::MoveToPoseGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::MoveToPoseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80b130a384062a7ab02c42399d5fceca";
  }

  static const char* value(const ::robot_msgs::MoveToPoseGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80b130a384062a7aULL;
  static const uint64_t static_value2 = 0xb02c42399d5fcecaULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::MoveToPoseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/MoveToPoseGoal";
  }

  static const char* value(const ::robot_msgs::MoveToPoseGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::MoveToPoseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"geometry_msgs/Pose2D target_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::robot_msgs::MoveToPoseGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::MoveToPoseGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveToPoseGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::MoveToPoseGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::MoveToPoseGoal_<ContainerAllocator>& v)
  {
    s << indent << "target_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.target_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_MOVETOPOSEGOAL_H
