// Generated by gencpp from file robot_msgs/MoveToPoseFeedback.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_MOVETOPOSEFEEDBACK_H
#define ROBOT_MSGS_MESSAGE_MOVETOPOSEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct MoveToPoseFeedback_
{
  typedef MoveToPoseFeedback_<ContainerAllocator> Type;

  MoveToPoseFeedback_()
    : percentage(0.0)  {
    }
  MoveToPoseFeedback_(const ContainerAllocator& _alloc)
    : percentage(0.0)  {
  (void)_alloc;
    }



   typedef float _percentage_type;
  _percentage_type percentage;





  typedef boost::shared_ptr< ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToPoseFeedback_

typedef ::robot_msgs::MoveToPoseFeedback_<std::allocator<void> > MoveToPoseFeedback;

typedef boost::shared_ptr< ::robot_msgs::MoveToPoseFeedback > MoveToPoseFeedbackPtr;
typedef boost::shared_ptr< ::robot_msgs::MoveToPoseFeedback const> MoveToPoseFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator1> & lhs, const ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percentage == rhs.percentage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator1> & lhs, const ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a2e49c0d6ad0ad2cee62709e672c242a";
  }

  static const char* value(const ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa2e49c0d6ad0ad2cULL;
  static const uint64_t static_value2 = 0xee62709e672c242aULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/MoveToPoseFeedback";
  }

  static const char* value(const ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"float32 percentage\n"
;
  }

  static const char* value(const ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveToPoseFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::MoveToPoseFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percentage: ";
    Printer<float>::stream(s, indent + "  ", v.percentage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_MOVETOPOSEFEEDBACK_H
