// Auto-generated. Do not edit!

// (in-package robot_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class MoveToPoseResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.success = null;
      this.distance_error = null;
      this.angle_error = null;
    }
    else {
      if (initObj.hasOwnProperty('success')) {
        this.success = initObj.success
      }
      else {
        this.success = false;
      }
      if (initObj.hasOwnProperty('distance_error')) {
        this.distance_error = initObj.distance_error
      }
      else {
        this.distance_error = 0.0;
      }
      if (initObj.hasOwnProperty('angle_error')) {
        this.angle_error = initObj.angle_error
      }
      else {
        this.angle_error = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MoveToPoseResult
    // Serialize message field [success]
    bufferOffset = _serializer.bool(obj.success, buffer, bufferOffset);
    // Serialize message field [distance_error]
    bufferOffset = _serializer.float32(obj.distance_error, buffer, bufferOffset);
    // Serialize message field [angle_error]
    bufferOffset = _serializer.float32(obj.angle_error, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MoveToPoseResult
    let len;
    let data = new MoveToPoseResult(null);
    // Deserialize message field [success]
    data.success = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [distance_error]
    data.distance_error = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [angle_error]
    data.angle_error = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 9;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robot_msgs/MoveToPoseResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e10d40ae20ce81829989865e265c0534';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result
    bool success
    float32 distance_error
    float32 angle_error
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MoveToPoseResult(null);
    if (msg.success !== undefined) {
      resolved.success = msg.success;
    }
    else {
      resolved.success = false
    }

    if (msg.distance_error !== undefined) {
      resolved.distance_error = msg.distance_error;
    }
    else {
      resolved.distance_error = 0.0
    }

    if (msg.angle_error !== undefined) {
      resolved.angle_error = msg.angle_error;
    }
    else {
      resolved.angle_error = 0.0
    }

    return resolved;
    }
};

module.exports = MoveToPoseResult;
