(cl:defpackage robot_msgs-msg
  (:use )
  (:export
   "<ABC>"
   "ABC"
   "<MOVETOPOSEACTION>"
   "MOVETOPOSEACTION"
   "<MOVETOPOSEACTIONFEEDBACK>"
   "MOVETOPOSEACTIONFEEDBACK"
   "<MOVETOPOSEACTIONGOAL>"
   "MOVETOPOSEACTIONGOAL"
   "<MOVETOPOSEACTIONRESULT>"
   "MOVETOPOSEACTIONRESULT"
   "<MOVETOPOSEFEEDBACK>"
   "MOVETOPOSEFEEDBACK"
   "<MOVETOPOSEGOAL>"
   "MOVETOPOSEGOAL"
   "<MOVETOPOSERESULT>"
   "MOVETOPOSERESULT"
  ))

