; Auto-generated. Do not edit!


(cl:in-package robot_msgs-msg)


;//! \htmlinclude MoveToPoseGoal.msg.html

(cl:defclass <MoveToPoseGoal> (roslisp-msg-protocol:ros-message)
  ((target_pose
    :reader target_pose
    :initarg :target_pose
    :type geometry_msgs-msg:Pose2D
    :initform (cl:make-instance 'geometry_msgs-msg:Pose2D)))
)

(cl:defclass MoveToPoseGoal (<MoveToPoseGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveToPoseGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveToPoseGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_msgs-msg:<MoveToPoseGoal> is deprecated: use robot_msgs-msg:MoveToPoseGoal instead.")))

(cl:ensure-generic-function 'target_pose-val :lambda-list '(m))
(cl:defmethod target_pose-val ((m <MoveToPoseGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_msgs-msg:target_pose-val is deprecated.  Use robot_msgs-msg:target_pose instead.")
  (target_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveToPoseGoal>) ostream)
  "Serializes a message object of type '<MoveToPoseGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'target_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveToPoseGoal>) istream)
  "Deserializes a message object of type '<MoveToPoseGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'target_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveToPoseGoal>)))
  "Returns string type for a message object of type '<MoveToPoseGoal>"
  "robot_msgs/MoveToPoseGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveToPoseGoal)))
  "Returns string type for a message object of type 'MoveToPoseGoal"
  "robot_msgs/MoveToPoseGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveToPoseGoal>)))
  "Returns md5sum for a message object of type '<MoveToPoseGoal>"
  "80b130a384062a7ab02c42399d5fceca")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveToPoseGoal)))
  "Returns md5sum for a message object of type 'MoveToPoseGoal"
  "80b130a384062a7ab02c42399d5fceca")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveToPoseGoal>)))
  "Returns full string definition for message of type '<MoveToPoseGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%geometry_msgs/Pose2D target_pose~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# Deprecated~%# Please use the full 3D pose.~%~%# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.~%~%# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.~%~%~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveToPoseGoal)))
  "Returns full string definition for message of type 'MoveToPoseGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%geometry_msgs/Pose2D target_pose~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# Deprecated~%# Please use the full 3D pose.~%~%# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.~%~%# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.~%~%~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveToPoseGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'target_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveToPoseGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveToPoseGoal
    (cl:cons ':target_pose (target_pose msg))
))
