; Auto-generated. Do not edit!


(cl:in-package robot_msgs-msg)


;//! \htmlinclude MoveToPoseResult.msg.html

(cl:defclass <MoveToPoseResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil)
   (distance_error
    :reader distance_error
    :initarg :distance_error
    :type cl:float
    :initform 0.0)
   (angle_error
    :reader angle_error
    :initarg :angle_error
    :type cl:float
    :initform 0.0))
)

(cl:defclass MoveToPoseResult (<MoveToPoseResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveToPoseResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveToPoseResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_msgs-msg:<MoveToPoseResult> is deprecated: use robot_msgs-msg:MoveToPoseResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <MoveToPoseResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_msgs-msg:success-val is deprecated.  Use robot_msgs-msg:success instead.")
  (success m))

(cl:ensure-generic-function 'distance_error-val :lambda-list '(m))
(cl:defmethod distance_error-val ((m <MoveToPoseResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_msgs-msg:distance_error-val is deprecated.  Use robot_msgs-msg:distance_error instead.")
  (distance_error m))

(cl:ensure-generic-function 'angle_error-val :lambda-list '(m))
(cl:defmethod angle_error-val ((m <MoveToPoseResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_msgs-msg:angle_error-val is deprecated.  Use robot_msgs-msg:angle_error instead.")
  (angle_error m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveToPoseResult>) ostream)
  "Serializes a message object of type '<MoveToPoseResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'distance_error))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'angle_error))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveToPoseResult>) istream)
  "Deserializes a message object of type '<MoveToPoseResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'distance_error) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'angle_error) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveToPoseResult>)))
  "Returns string type for a message object of type '<MoveToPoseResult>"
  "robot_msgs/MoveToPoseResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveToPoseResult)))
  "Returns string type for a message object of type 'MoveToPoseResult"
  "robot_msgs/MoveToPoseResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveToPoseResult>)))
  "Returns md5sum for a message object of type '<MoveToPoseResult>"
  "e10d40ae20ce81829989865e265c0534")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveToPoseResult)))
  "Returns md5sum for a message object of type 'MoveToPoseResult"
  "e10d40ae20ce81829989865e265c0534")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveToPoseResult>)))
  "Returns full string definition for message of type '<MoveToPoseResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool success~%float32 distance_error~%float32 angle_error~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveToPoseResult)))
  "Returns full string definition for message of type 'MoveToPoseResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool success~%float32 distance_error~%float32 angle_error~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveToPoseResult>))
  (cl:+ 0
     1
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveToPoseResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveToPoseResult
    (cl:cons ':success (success msg))
    (cl:cons ':distance_error (distance_error msg))
    (cl:cons ':angle_error (angle_error msg))
))
